### ISSUE TITLE
Doesn't render in browser

### ISSUE THREAD

**Issue by bitplanets** [thlorenz/bunyan-format#4]
You could even use css styles to render beautiful logs in chrome https://developer.chrome.com/devtools/docs/console#styling-console-output-with-css

**Comment by thlorenz** [comment]
This is meant to be used server side, but I'm open for a PR that adds the feature you describe.
Closing this issue for now.

**Comment by bitplanets** [comment]
It's more complex than just a formatter. I've done a hack over the original bunyan, there is an issue with the example https://github.com/trentm/node-bunyan/issues/214

**Comment by thlorenz** [comment]
That's nice, would you like to add this feature via a PR here via a similar _hack_?
